### PR TITLE
Mocking PROGMEM on non Arduino platforms

### PR DESCRIPTION
**Pull request by boscs**
Hey @FrankBoesing, 

I'd like to thank you first for this amazing library you brought us. It is VERY usefull :)
So useful in fact that I decided to include it in a large project that spans across multiple type of devices including the laptop I'm using to write this.
As I'm trying to load your module in a python vm (using cppyy), I realized that Progmem seems to create a compatibly issue (it is obviously not present in the compiler for x86).

I therefore added flags to replace it by nothing if not existent.

Hope you'll find this useful :)

Bye and thanks a lot for your work

### CODE REVIEW

**Comment by FrankBoesing** [comment]
Hi, thank you!. But what exactly is the issue?

**Comment by boscs** [comment]
if you try to import FastCRC.h in an x86 compiler (like the llvm one in the cppyy python module) it won't work because the "PROGMEM" declaration blocks it which is sad.

**Comment by FrankBoesing** [comment]
Thanks!

**Comment by boscs** [comment]
No! Thank you for your lib!

**Pull request merged**
